# RECADOS

### Lista todos os recados
GET http://localhost:3000/recados
?limit=100
&offset=200
### Busca apenas UM recado
GET http://localhost:3000/recados/2
### Cria um recado
POST http://localhost:3000/recados
Content-Type: application/json

  {
    "texto": "Este é um novo Recado",
    "de": "Guilherme",
    "para": "João",
    "lido": false,
    "data": "2025-01-06T09:51:04.778Z"
  }

### Atualiza um recado
PATCH http://localhost:3000/recados/2
Content-Type: application/json

  {
    "texto": "ATUALIZAR Recado",
    "de": "Guilherme",
    "para": "João",
    "lido": false,
    "data": "2025-01-06T09:51:04.778Z"
  }
### Remove apenas UM recado
DELETE http://localhost:3000/recados/1

### AppControllerGetHello

# @name AppControllerGetHello
GET http://localhost:3000/home/hello

### ConceitosManualController

# @name ConceitosManualController
GET http://localhost:3000/conceitos-manual

### ConceitosAutomaticoController

# @name ConceitosAutomaticoController
GET http://localhost:3000/conceitos-automatico