# RECADOS

### Lista todos os recados
GET http://localhost:3000/recados
?limit=10
&offset=0
Authorization: Bearer AquiSeuToken
### Busca apenas UM recado
GET http://localhost:3000/recados/4
### Cria um recado
POST http://localhost:3000/recados
Content-Type: application/json

  {
    "texto": "Este é um novo Recado",
    "deId": 5,
    "paraId": 5
  }

### Atualiza um recado
PATCH http://localhost:3000/recados/2
Content-Type: application/json

  {
    "texto": "ATUALIZAR Recado",
    "lido": false,
  }
### Remove apenas UM recado
DELETE http://localhost:3000/recados/1

### AppControllerGetHello

# @name AppControllerGetHello
GET http://localhost:3000/home/hello

### ConceitosManualController

# @name ConceitosManualController
GET http://localhost:3000/conceitos-manual

### ConceitosAutomaticoController

# @name ConceitosAutomaticoController
GET http://localhost:3000/conceitos-automatico


# PESSOAS

### Lista todas as pessoas
GET http://localhost:3000/pessoas
?limit=100
&offset=200
### Busca apenas UMA pessoa
GET http://localhost:3000/pessoas/1
### Cria uma pessoa
POST http://localhost:3000/pessoas
Content-Type: application/json

  {
    "email": "guilherme@mail.com",
    "nome": "Guilherme",
    "password": "123456"
  }
### Atualiza um recado
PATCH http://localhost:3000/pessoas/5
Content-Type: application/json

  {
    "nome": "João",
    "password": "123456"
  }
### Remove apenas UM recado
DELETE http://localhost:3000/pessoas/1
